CREATE TABLE USER_RECORD (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USER_NAME VARCHAR(16) NOT NULL,
	GAME_TYPE INTEGER NOT NULL,
	USER_DATA BLOB NOT NULL
);
CREATE UNIQUE INDEX GAME_NAME ON USER_RECORD(GAME_TYPE, USER_NAME);
